### ISSUE TITLE
[Documentation]: broken/externally inaccessible links

### ISSUE THREAD

**Issue by maartenarnst** [ROCm/rocprofiler-sdk#2]
### Description of errors

The readme file with the project description contains links that are broken or inaccessible from outside amd. Such as the link to the rocprofv3 tool.

**Comment by ammarwa** [comment]
This should be fixed by now in the latest amd-mainline.

Thank you!

**Comment by ammarwa** [comment]
Please feel free to reopen if the issue still exists.
